name: Generate README Stats Cards 📊

on:
  schedule:
    - cron: "10 0 * * *" # todo dia 00:10 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate top languages card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: top-langs
          options: 'username=${{ github.repository_owner }}&layout=compact&theme=tokyonight'
          path: dist/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # opcional (card principal)
      - name: Generate stats card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: stats
          options: 'username=${{ github.repository_owner }}&show_icons=true&theme=tokyonight'
          path: dist/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
